# Copyright (C) 2021 The Authors of CEL-Java
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Release

on:
  # Manually triggered
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'The version to release - e.g. `0.5.0`'
        required: true
      nextVersion:
        description: 'The NEXT version to release - e.g. `0.6.0` without the -SNAPSHOT suffix'
        required: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      GIT_TAG: v${{ github.event.inputs.releaseVersion }}
      RELEASE_VERSION: ${{ github.event.inputs.releaseVersion }}
      NEXT_VERSION: ${{ github.event.inputs.nextVersion }}

    steps:
      - name: Check parameters
        run: |
          if [[ ${RELEASE_VERSION} =~ ^[0-9]+[.][0-9.]*[0-9](-[a-zA-Z0-9]+)?$ ]]; then
            echo "Parameter check for 'releaseVersion' OK"
          else
            echo "Parameter check for 'releaseVersion' failed"
            exit 1
          fi
          if [[ ${NEXT_VERSION} =~ ^[0-9]+[.][0-9.]*[0-9](-[a-zA-Z0-9]+)?$ ]]; then
            echo "Parameter check for 'nextVersion' OK"
          else
            echo "Parameter check for 'nextVersion' failed"
            exit 1
          fi
      - name: Check commit status
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
          gh api repos/projectnessie/cel-java/commits/${GITHUB_SHA}/check-runs --jq 'if ([.check_runs[] | select(.name | endswith("Release") or startswith("codecov/") or startswith("Report") | not ) | .conclusion // "pending" ] | unique == ["success"]) then "OK" else error("Commit checks are not OK") end'

      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ matrix.java-version }}-${{ hashFiles('**/*.gradle.kts') }}-${{ hashFiles('**/.gitmodules') }}
          restore-keys: gradle-${{ matrix.java-version }}

      - name: Configure release-bot-user in git config
        run: |
          git config --global user.email "cel-java-release-noreply@projectnessie.org"
          git config --global user.name "CEL-Java Release Workflow [bot]"

      - name: Bump to release version
        run: echo "${RELEASE_VERSION}" > version.txt

      - name: Record ${{ github.event.inputs.releaseVersion }} release in git
        run: |
          git commit -a -m "[release] v${RELEASE_VERSION}"
          git tag -f ${GIT_TAG}

      - name: Publish to Sonatype
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.OSSRH_ACCESS_ID }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.OSSRH_TOKEN }}
        run: ./gradlew --rerun-tasks --no-daemon --info assemble check publishToMavenLocal -x jmh publishToSonatype closeAndReleaseSonatypeStagingRepository

      - name: Bump to next development version
        run: echo "${NEXT_VERSION}-SNAPSHOT" > version.txt

      - name: Record next development version in git
        run: git commit -a -m "[release] next development version ${NEXT_VERSION}"

      - name: Push tag + branch
        run: |
          # Push directly using the remote repo URL, which includes the secret so this job can push to the repo
          UPSTREAM="https://${{ secrets.NESSIE_BUILDER }}@github.com/${GITHUB_REPOSITORY}.git"

          # Move the default auth settings in ~/.gitconfig out of the way, so the git-push can use the token
          git config --rename-section http.https://github.com/ http.https://save.github.com/

          git push --no-verify "${UPSTREAM}" HEAD:${GITHUB_REF} ${GIT_TAG}

          # Move the default auth settings in ~/.gitconfig back
          git config --rename-section http.https://save.github.com/ http.https://github.com/

      - name: Prepare Release Notes
        id: prep_release
        run: |
          git fetch --tags

          DIR=$(mktemp -d)
          NOTES_FILE=${DIR}/release-notes.md
          LAST_TAG=$(git describe --tags --abbrev=0 HEAD^1)
          NUM_COMMITS=$(git log --format='format:%h' ${LAST_TAG}..HEAD | wc -l)

          csplit site/docs/try/releases.md '%##%' {0} '/##/' {0} '%##%' {*} -f ${DIR}/release-highlights -b '-%d.txt' > /dev/null

          git log --perl-regexp --author '^(?!.*dependabot|.*cel-java-release-workflow).*$' --format='format:* %s' ${LAST_TAG}..${GIT_TAG} | grep -v '^\* \[release\] .*$' > ${DIR}/release-log

          cat <<EOF > ${DIR}/release-notes.md
          # Highlights

          * ${NUM_COMMITS} commits since ${LAST_TAG#v}
          $(cat ${DIR}/release-highlights* | grep -v '^[#][#] .*$' | grep -v '^$' | sed 's/^(.*)$/* $1/')

          ## Full Changelog (minus dependabot commits):

          $(cat ${DIR}/release-log)
          EOF

          echo ::set-output name=NOTES_FILE::${NOTES_FILE}

      - name: Create Release in GitHub
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
          gh release create ${GIT_TAG} --notes-file ${{ steps.prep_release.outputs.NOTES_FILE }} --title "CEL-Java ${RELEASE_VERSION}"
